package com.yqy.entity;

public class RUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.ID_USER
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private Long idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.LOGIN
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private String login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.PASSWORD
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.NAME
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.DESCRIPTION
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.ENABLED
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.ID_USER
     *
     * @return the value of r_user.ID_USER
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.ID_USER
     *
     * @param idUser the value for r_user.ID_USER
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.LOGIN
     *
     * @return the value of r_user.LOGIN
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.LOGIN
     *
     * @param login the value for r_user.LOGIN
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.PASSWORD
     *
     * @return the value of r_user.PASSWORD
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.PASSWORD
     *
     * @param password the value for r_user.PASSWORD
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.NAME
     *
     * @return the value of r_user.NAME
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.NAME
     *
     * @param name the value for r_user.NAME
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.DESCRIPTION
     *
     * @return the value of r_user.DESCRIPTION
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.DESCRIPTION
     *
     * @param description the value for r_user.DESCRIPTION
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.ENABLED
     *
     * @return the value of r_user.ENABLED
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.ENABLED
     *
     * @param enabled the value for r_user.ENABLED
     *
     * @mbg.generated Sat Jun 27 19:13:56 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}